You will use the values of what you find in this assignment to answer questions in the quiz that follows. You may want to open this notebook to be displayed side-by-side on screen with this next quiz.

1. Write a function that inputs an integers and returns the negative

In [ ]:
# Write your function here
def negative_rtn(x):
    out = -(x)
    return out

In [ ]:
# Test your function with input x
negative_rtn(4)

2. Write a function that inputs a list of integers and returns the minimum value

In [ ]:
# Write your function here
def get_min(x):
    current_min = x[0]
    for i in x[1:]:
        if i < current_min:
            current_min = i
    return current_min

In [ ]:
# Test your function with input lst
lst = [-3, 0, 2, 100, -1, 2]
get_min(lst)


# Create you own input list to test with

#### Challenge problem:  
Write a function that take in four arguments: lst1, lst2, str1, str2, and returns a pandas DataFrame that has the first column labeled str1 and the second column labaled str2, that have values lst1 and lst2 scaled to be between 0 and 1.

For example
```
lst1 = [1, 2, 3]
lst2 = [2, 4, 5]
str1 = 'one'
str2 = 'two'

my_function(lst1, lst2, str1, str2)
``` 
should return a DataFrame that looks like:



|  <i></i> | one | two |
| --- | --- | --- |
| 0 | 0 | 0 |
| 1 | .5 | .666 |
| 2 | 1 | 1 |

0.4242749731471536
0.3952738990332975
0.8678839957035446
0.37808807733619765
-0.16004296455424274
0.3233082706766917
0.5617615467239527
0.6380236305048335
0.21804511278195488
0.8990332975295381
0.5789473684210527
0.966702470461869
0.021482277121374866
0.5456498388829216
0.4833512352309345
0.07518796992481203
-0.20730397422126745
0.6476906552094522
-0.2513426423200859
-0.045112781954887216
0.9301825993555317
0.5037593984962406
0.5166487647690655
0.920515574650913
-0.14500537056928034
0.22234156820622986
0.01611170784103115
-0.01288936627282492
0.45757250268528465
0.00322234156820623
0.6143931256713212
0.3952738990332975
0.7303974221267454
0.6272824919441461
-0.24919441460794844
-0.2083780880773362
0.9291084854994629
0.7604726100966702
0.9344790547798066
0.7400644468313641
0.4113856068743287
-0.024704618689581095
0.7475832438238453
0.46186895810955964
0.01611170784103115
0.34801288936627284
0.35123523093447906
0.6100966702470462
0.7293233082706767
0.3071965628356606
0.6552094522019334
0.1364124597207304
0.9377013963480129
-0.08378088077336197
0.0053705692803437165
0.518796992481203
0.23523093447905477
0.3383458646616541
0.5907626208378088
0.6595059076262084
0.7604726100966702
0.6294307196562836
0.06874328678839957
0.06659505907626208
0.11600429645542427
-0.22878625134264233
0.920515574650913
0.5596133190118152
0.25241675617615467
-0.23200859291084855
0.05263157894736842
0.00644468313641246
0.8259935553168636
0.35660580021482274
0.38990332975295383
0.0397422126745435
1.0
0.9538131041890441
0.32867883995703545
0.37056928034371645
0.00644468313641246
-0.18259935553168635
0.07841031149301826
-0.09237379162191192
0.24274973147153597
0.06766917293233082
0.10526315789473684
0.43609022556390975
0.7056928034371643
0.765843179377014
-0.14285714285714285
0.5488721804511278
0.9366272824919442
0.22126745435016112
0.7733619763694952
-0.18152524167561762
0.7261009667024705
0.9462943071965628
0.9935553168635876
0.04189044038668099

         one     alpha
0   0.539914  0.217868
1   0.516738  0.128527
2   0.894421  0.326019
3   0.503004  0.890282
4   0.072961  0.678683
5   0.459227  0.365204
6   0.649785  0.568966
7   0.710730  0.064263
8   0.375107  0.387147
9   0.919313  0.047022
10  0.663519  0.454545
11  0.973391  0.059561
12  0.218026  0.708464
13  0.636910  0.957680
14  0.587124  0.890282
15  0.260944  0.976489
16  0.035193  0.512539
17  0.718455  0.448276
18  0.000000  0.561129
19  0.164807  0.158307
20  0.944206  0.755486
21  0.603433  0.285266
22  0.613734  0.252351
23  0.936481  0.277429
24  0.084979  0.318182
25  0.378541  0.351097
26  0.213734  0.611285
27  0.190558  0.717868
28  0.566524  0.402821
29  0.203433  0.152038
..       ...       ...
70  0.242918  0.716301
71  0.206009  0.805643
72  0.860944  0.166144
73  0.485837  0.620690
74  0.512446  0.564263
75  0.232618  0.130094
76  1.000000  0.115987
77  0.963090  0.482759
78  0.463519  0.510972
79  0.496996  0.211599
80  0.206009  0.545455
81  0.054936  0.280564
82  0.263519  0.658307
83  0.127039  0.496865
84  0.394850  0.219436
85  0.254936  0.927900
86  0.284979  0.949843
87  0.549356  0.664577
88  0.764807  0.515674
89  0.812876  0.642633
90  0.086695  0.611285
91  0.639485  0.051724
92  0.949356  0.808777
93  0.377682  0.282132
94  0.818884  0.951411
95  0.055794  0.473354
96  0.781116  0.641066
97  0.957082  0.202194
98  0.994850  0.000000
99  0.234335  0.677116

[100 rows x 2 columns]

In [17]:
import numpy as np
import pandas as pd


def my_function(lst1, lst2, str1, str2):
    
    mx_1 = max(lst1)
    mn_1 = min(lst1)
    lst3 = []
    lst4 = []
    for key in lst1:
        k = ((key-mn_1)/(mx_1-mn_1))
        lst3.append(k)
    mx_2 = max(lst2)
    mn_2 = min(lst2)
    for key in lst2:
        k =((key-mn_2)/(mx_2-mn_2))
        lst4.append(k)
    
    return pd.DataFrame({str1 : lst3 , str2 : lst4})

In [18]:
lst1 = [1, 2, 3]
lst2 = [2, 4, 5]
str1 = 'one'
str2 = 'two'
my_function(lst1, lst2, str1, str2)

   one       two
0  0.0  0.000000
1  0.5  0.666667
2  1.0  1.000000

In [19]:
# test your challenge problem function
import numpy as np

lst1 = np.random.randint(-234, 938, 100)
lst2 = np.random.randint(-522, 123, 100)
str1 = 'one'
str2 = 'alpha'
my_function(lst1, lst2, str1, str2)

         one     alpha
0   0.139896  0.089577
1   0.065630  0.276873
2   0.224525  0.498371
3   0.677029  0.057003
4   0.986183  0.532573
5   0.613990  0.063518
6   0.085492  0.868078
7   0.955959  0.959283
8   0.258204  0.351792
9   0.000000  0.167752
10  0.944732  0.110749
11  0.869603  0.916938
12  0.213299  0.970684
13  0.743523  0.055375
14  0.860104  0.716612
15  0.322107  0.620521
16  0.146805  0.820847
17  0.950777  0.657980
18  0.316062  0.926710
19  0.911054  0.278502
20  0.835924  0.802932
21  0.056131  0.167752
22  0.246978  0.970684
23  0.968912  0.519544
24  0.856649  0.071661
25  0.514680  0.594463
26  0.080311  0.661238
27  0.041451  0.057003
28  0.644214  0.074919
29  0.195164  0.115635
..       ...       ...
70  0.344560  0.200326
71  0.629534  0.337134
72  0.085492  0.641694
73  0.742660  0.662866
74  0.719344  0.724756
75  0.613990  0.815961
76  0.429188  0.482085
77  0.727979  0.543974
78  0.531088  0.457655
79  0.165803  0.820847
80  0.018998  0.970684
81  0.266839  0.255700
82  0.331606  0.105863
83  1.000000  0.464169
84  0.827288  0.140065
85  0.338515  0.680782
86  0.403282  0.045603
87  0.696891  0.765472
88  0.218480  0.902280
89  0.945596  0.915309
90  0.408463  0.622150
91  0.278066  0.384365
92  0.882556  0.970684
93  0.101900  0.374593
94  0.017271  0.245928
95  0.912781  0.486971
96  0.081174  0.086319
97  0.939551  0.161238
98  0.362694  0.986971
99  0.690846  0.589577

[100 rows x 2 columns]